# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rake secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: 1dde67f1644c1033bfa0f7fe16adf66000ac967ac096e7a839bd568e82dec1b672000cf8c829839768a8b46168b7ebc989dfa129e53a3b21b68d3e483c14f1cd

test:
  secret_key_base: cb85efb2d45f3ecdb1cc6ae839322e3a03853bfcf2077c41b9da5b2fed6937d2e8739101dba5a4a97c29a112d850b75b6bc88767504d32825186eb49a22e7385

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
